- pkg:apk/alpine/grafana@10.2.2-r3?arch=aarch64&distro=v3.19
- pkg:apk/alpine/grafana@10.2.2-r3?arch=ppc64le&distro=v3.19
- pkg:apk/alpine/grafana@10.2.2-r3?arch=x86_64&distro=v3.19
- pkg:apk/alpine/grafana@11.0.8-r0?arch=aarch64&distro=v3.20
- pkg:apk/alpine/grafana@11.0.8-r0?arch=ppc64le&distro=v3.20
- pkg:apk/alpine/grafana@11.0.8-r0?arch=s390x&distro=v3.20
- pkg:apk/alpine/grafana@11.0.8-r0?arch=x86_64&distro=v3.20
- pkg:apk/alpine/grafana@11.3.1-r5?arch=aarch64&distro=v3.21
- pkg:apk/alpine/grafana@11.3.1-r5?arch=loongarch64&distro=v3.21
- pkg:apk/alpine/grafana@11.3.1-r5?arch=ppc64le&distro=v3.21
- pkg:apk/alpine/grafana@11.3.1-r5?arch=riscv64&distro=v3.21
- pkg:apk/alpine/grafana@11.3.1-r5?arch=s390x&distro=v3.21
- pkg:apk/alpine/grafana@11.3.1-r5?arch=x86_64&distro=v3.21
- pkg:apk/alpine/grafana@12.0.0-r3?arch=riscv64&distro=v3.22
- pkg:apk/alpine/grafana@12.0.0-r4?arch=aarch64&distro=v3.22
- pkg:apk/alpine/grafana@12.0.0-r4?arch=loongarch64&distro=v3.22
- pkg:apk/alpine/grafana@12.0.0-r4?arch=ppc64le&distro=v3.22
- pkg:apk/alpine/grafana@12.0.0-r4?arch=riscv64&distro=v3.22
- pkg:apk/alpine/grafana@12.0.0-r4?arch=s390x&distro=v3.22
- pkg:apk/alpine/grafana@12.0.0-r4?arch=x86_64&distro=v3.22
- pkg:apk/alpine/grafana@12.0.0-r5?arch=aarch64&distro=v3.22
- pkg:apk/alpine/grafana@12.0.0-r5?arch=loongarch64&distro=v3.22
- pkg:apk/alpine/grafana@12.0.0-r5?arch=ppc64le&distro=v3.22
- pkg:apk/alpine/grafana@12.0.0-r5?arch=s390x&distro=v3.22
- pkg:apk/alpine/grafana@12.0.0-r5?arch=x86_64&distro=v3.22
- pkg:apk/alpine/grafana@12.2.1-r0?arch=riscv64&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r0?arch=riscv64&distro=latest-stable
- pkg:apk/alpine/grafana@12.2.1-r1?arch=aarch64&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r1?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/grafana@12.2.1-r1?arch=loongarch64&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r1?arch=loongarch64&distro=latest-stable
- pkg:apk/alpine/grafana@12.2.1-r1?arch=ppc64le&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r1?arch=ppc64le&distro=latest-stable
- pkg:apk/alpine/grafana@12.2.1-r1?arch=riscv64&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r1?arch=riscv64&distro=latest-stable
- pkg:apk/alpine/grafana@12.2.1-r1?arch=s390x&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r1?arch=s390x&distro=latest-stable
- pkg:apk/alpine/grafana@12.2.1-r1?arch=x86_64&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r1?arch=x86_64&distro=latest-stable
- pkg:apk/alpine/grafana@12.2.1-r2?arch=aarch64&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r2?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/grafana@12.2.1-r2?arch=loongarch64&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r2?arch=loongarch64&distro=latest-stable
- pkg:apk/alpine/grafana@12.2.1-r2?arch=ppc64le&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r2?arch=ppc64le&distro=latest-stable
- pkg:apk/alpine/grafana@12.2.1-r2?arch=riscv64&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r2?arch=riscv64&distro=latest-stable
- pkg:apk/alpine/grafana@12.2.1-r2?arch=s390x&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r2?arch=s390x&distro=latest-stable
- pkg:apk/alpine/grafana@12.2.1-r2?arch=x86_64&distro=edge
- pkg:apk/alpine/grafana@12.2.1-r2?arch=x86_64&distro=latest-stable
- pkg:apk/alpine/grafana@7.3.6-r0?arch=aarch64&distro=v3.13
- pkg:apk/alpine/grafana@7.3.6-r0?arch=armhf&distro=v3.13
- pkg:apk/alpine/grafana@7.3.6-r0?arch=armv7&distro=v3.13
- pkg:apk/alpine/grafana@7.3.6-r0?arch=ppc64le&distro=v3.13
- pkg:apk/alpine/grafana@7.3.6-r0?arch=s390x&distro=v3.13
- pkg:apk/alpine/grafana@7.3.6-r0?arch=x86&distro=v3.13
- pkg:apk/alpine/grafana@7.3.6-r0?arch=x86_64&distro=v3.13
- pkg:apk/alpine/grafana@7.5.7-r2?arch=mips64&distro=v3.14
- pkg:apk/alpine/grafana@7.5.7-r4?arch=aarch64&distro=v3.14
- pkg:apk/alpine/grafana@7.5.7-r4?arch=armhf&distro=v3.14
- pkg:apk/alpine/grafana@7.5.7-r4?arch=armv7&distro=v3.14
- pkg:apk/alpine/grafana@7.5.7-r4?arch=ppc64le&distro=v3.14
- pkg:apk/alpine/grafana@7.5.7-r4?arch=s390x&distro=v3.14
- pkg:apk/alpine/grafana@7.5.7-r4?arch=x86&distro=v3.14
- pkg:apk/alpine/grafana@7.5.7-r4?arch=x86_64&distro=v3.14
- pkg:apk/alpine/grafana@8.2.7-r2?arch=aarch64&distro=v3.15
- pkg:apk/alpine/grafana@8.2.7-r2?arch=armhf&distro=v3.15
- pkg:apk/alpine/grafana@8.2.7-r2?arch=armv7&distro=v3.15
- pkg:apk/alpine/grafana@8.2.7-r2?arch=ppc64le&distro=v3.15
- pkg:apk/alpine/grafana@8.2.7-r2?arch=x86&distro=v3.15
- pkg:apk/alpine/grafana@8.2.7-r2?arch=x86_64&distro=v3.15
- pkg:apk/alpine/grafana@8.5.13-r1?arch=aarch64&distro=v3.16
- pkg:apk/alpine/grafana@8.5.13-r1?arch=ppc64le&distro=v3.16
- pkg:apk/alpine/grafana@8.5.13-r1?arch=x86&distro=v3.16
- pkg:apk/alpine/grafana@8.5.13-r1?arch=x86_64&distro=v3.16
- pkg:apk/alpine/grafana@9.2.5-r4?arch=aarch64&distro=v3.17
- pkg:apk/alpine/grafana@9.2.5-r4?arch=ppc64le&distro=v3.17
- pkg:apk/alpine/grafana@9.2.5-r4?arch=x86_64&distro=v3.17
- pkg:apk/alpine/grafana@9.5.2-r4?arch=aarch64&distro=v3.18
- pkg:apk/alpine/grafana@9.5.2-r4?arch=ppc64le&distro=v3.18
- pkg:apk/alpine/grafana@9.5.2-r4?arch=x86_64&distro=v3.18
