- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r5?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r5?arch=riscv64&distro=latest-stable
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=armhf&distro=latest-stable
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=armv7&distro=latest-stable
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=ppc64le&distro=latest-stable
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=riscv64&distro=latest-stable
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=s390x&distro=latest-stable
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=x86&distro=edge
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=x86&distro=latest-stable
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r6?arch=x86_64&distro=latest-stable
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r7?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r7?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-apcupsd-exporter@0.3.0-r7?arch=s390x&distro=edge
