- pkg:apk/alpine/prometheus-blackbox-exporter@0.27.0-r4?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-blackbox-exporter@0.27.0-r4?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-blackbox-exporter@0.27.0-r4?arch=armv7&distro=edge
