- pkg:apk/alpine/prometheus-smartctl-exporter@0.14.0-r4?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-smartctl-exporter@0.14.0-r5?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-smartctl-exporter@0.14.0-r5?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-smartctl-exporter@0.14.0-r5?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-smartctl-exporter@0.14.0-r5?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-smartctl-exporter@0.14.0-r5?arch=ppc64le&distro=edge
