- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r14?arch=aarch64&distro=v3.21
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r14?arch=armhf&distro=v3.21
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r14?arch=armv7&distro=v3.21
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r14?arch=loongarch64&distro=v3.21
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r14?arch=ppc64le&distro=v3.21
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r14?arch=x86&distro=v3.21
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r14?arch=x86_64&distro=v3.21
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r17?arch=riscv64&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r18?arch=aarch64&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r18?arch=armhf&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r18?arch=armv7&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r18?arch=loongarch64&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r18?arch=ppc64le&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r18?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r18?arch=riscv64&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r18?arch=riscv64&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r18?arch=s390x&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r18?arch=x86&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r18?arch=x86_64&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=aarch64&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=armhf&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=armhf&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=armv7&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=armv7&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=loongarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=loongarch64&distro=v3.22
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=ppc64le&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=riscv64&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=s390x&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=x86&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=x86&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r19?arch=x86_64&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r20?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r20?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r20?arch=armhf&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r20?arch=armv7&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r20?arch=loongarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r20?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r20?arch=ppc64le&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r20?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r20?arch=s390x&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r20?arch=x86&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r20?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r20?arch=x86_64&distro=latest-stable
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r7?arch=aarch64&distro=v3.19
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r7?arch=armhf&distro=v3.19
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r7?arch=armv7&distro=v3.19
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r7?arch=ppc64le&distro=v3.19
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r7?arch=x86&distro=v3.19
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r7?arch=x86_64&distro=v3.19
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r9?arch=aarch64&distro=v3.20
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r9?arch=armhf&distro=v3.20
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r9?arch=armv7&distro=v3.20
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r9?arch=ppc64le&distro=v3.20
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r9?arch=x86&distro=v3.20
- pkg:apk/alpine/prometheus-libvirt-exporter-openrc@2.3.3-r9?arch=x86_64&distro=v3.20
