- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=armv7&distro=edge
