- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r17?arch=aarch64&distro=v3.19
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r17?arch=armhf&distro=v3.19
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r29?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r29?arch=riscv64&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=armhf&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=armv7&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=loongarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=ppc64le&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=s390x&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=x86&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=x86&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-openrc-exporter-openrc@0.0.2-r30?arch=x86_64&distro=latest-stable
