- pkg:apk/alpine/prometheus-opnsense-exporter@0.0.11-r1?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-opnsense-exporter@0.0.11-r2?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-opnsense-exporter@0.0.11-r2?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-opnsense-exporter@0.0.11-r2?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-opnsense-exporter@0.0.11-r2?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-opnsense-exporter@0.0.11-r2?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-opnsense-exporter@0.0.11-r2?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-opnsense-exporter@0.0.11-r2?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-opnsense-exporter@0.0.11-r2?arch=x86&distro=edge
- pkg:apk/alpine/prometheus-opnsense-exporter@0.0.11-r2?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-opnsense-exporter@0.0.11-r3?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-opnsense-exporter@0.0.11-r3?arch=s390x&distro=edge
