- pkg:apk/alpine/prometheus-blackbox-exporter-openrc@0.27.0-r4?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-blackbox-exporter-openrc@0.27.0-r4?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-blackbox-exporter-openrc@0.27.0-r4?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-blackbox-exporter-openrc@0.27.0-r4?arch=loongarch64&distro=edge
