- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r7?arch=aarch64&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r7?arch=armhf&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r7?arch=armv7&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r7?arch=loongarch64&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r7?arch=ppc64le&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r7?arch=s390x&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r7?arch=x86&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r7?arch=x86_64&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r8?arch=aarch64&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r8?arch=armhf&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r8?arch=armv7&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r8?arch=loongarch64&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r8?arch=ppc64le&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r8?arch=s390x&distro=edge
- pkg:apk/alpine/ruuvi-prometheus@0.1.9-r8?arch=x86_64&distro=edge
