- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r3?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r4?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r4?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r4?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r4?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-snmp-exporter-openrc@0.29.0-r4?arch=ppc64le&distro=edge
