- pkg:apk/alpine/prometheus-ceph-exporter@4.2.5-r10?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-ceph-exporter@4.2.5-r10?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-ceph-exporter@4.2.5-r8?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-ceph-exporter@4.2.5-r9?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-ceph-exporter@4.2.5-r9?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-ceph-exporter@4.2.5-r9?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-ceph-exporter@4.2.5-r9?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-ceph-exporter@4.2.5-r9?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-ceph-exporter@4.2.5-r9?arch=x86_64&distro=edge
