- pkg:apk/alpine/ruuvi-prometheus-openrc@0.1.9-r7?arch=aarch64&distro=edge
- pkg:apk/alpine/ruuvi-prometheus-openrc@0.1.9-r7?arch=armhf&distro=edge
- pkg:apk/alpine/ruuvi-prometheus-openrc@0.1.9-r7?arch=armv7&distro=edge
