- pkg:apk/alpine/alertmanager-openrc@0.29.0-r1?arch=aarch64&distro=edge
- pkg:apk/alpine/alertmanager-openrc@0.29.0-r1?arch=armhf&distro=edge
- pkg:apk/alpine/alertmanager-openrc@0.29.0-r1?arch=armv7&distro=edge
- pkg:apk/alpine/alertmanager-openrc@0.29.0-r1?arch=loongarch64&distro=edge
