- pkg:apk/alpine/prometheus-openrc@3.5.0-r3?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-openrc@3.5.0-r3?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-openrc@3.5.0-r3?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-openrc@3.5.0-r3?arch=x86_64&distro=edge
