- pkg:apk/alpine/prometheus-openrc@2.14.0-r2?arch=aarch64&distro=v3.11
- pkg:apk/alpine/prometheus-openrc@2.14.0-r2?arch=armhf&distro=v3.11
- pkg:apk/alpine/prometheus-openrc@2.14.0-r2?arch=armv7&distro=v3.11
- pkg:apk/alpine/prometheus-openrc@2.14.0-r2?arch=ppc64le&distro=v3.11
- pkg:apk/alpine/prometheus-openrc@2.14.0-r2?arch=s390x&distro=v3.11
- pkg:apk/alpine/prometheus-openrc@2.14.0-r2?arch=x86&distro=v3.11
- pkg:apk/alpine/prometheus-openrc@2.14.0-r2?arch=x86_64&distro=v3.11
- pkg:apk/alpine/prometheus-openrc@2.18.2-r0?arch=aarch64&distro=v3.12
- pkg:apk/alpine/prometheus-openrc@2.18.2-r0?arch=armhf&distro=v3.12
- pkg:apk/alpine/prometheus-openrc@2.18.2-r0?arch=armv7&distro=v3.12
- pkg:apk/alpine/prometheus-openrc@2.18.2-r0?arch=ppc64le&distro=v3.12
- pkg:apk/alpine/prometheus-openrc@2.18.2-r0?arch=s390x&distro=v3.12
- pkg:apk/alpine/prometheus-openrc@2.18.2-r0?arch=x86&distro=v3.12
- pkg:apk/alpine/prometheus-openrc@2.18.2-r0?arch=x86_64&distro=v3.12
- pkg:apk/alpine/prometheus-openrc@2.24.0-r0?arch=aarch64&distro=v3.13
- pkg:apk/alpine/prometheus-openrc@2.24.0-r0?arch=armhf&distro=v3.13
- pkg:apk/alpine/prometheus-openrc@2.24.0-r0?arch=armv7&distro=v3.13
- pkg:apk/alpine/prometheus-openrc@2.24.0-r0?arch=ppc64le&distro=v3.13
- pkg:apk/alpine/prometheus-openrc@2.24.0-r0?arch=s390x&distro=v3.13
- pkg:apk/alpine/prometheus-openrc@2.24.0-r0?arch=x86&distro=v3.13
- pkg:apk/alpine/prometheus-openrc@2.24.0-r0?arch=x86_64&distro=v3.13
- pkg:apk/alpine/prometheus-openrc@2.27.1-r3?arch=aarch64&distro=v3.14
- pkg:apk/alpine/prometheus-openrc@2.27.1-r3?arch=armhf&distro=v3.14
- pkg:apk/alpine/prometheus-openrc@2.27.1-r3?arch=armv7&distro=v3.14
- pkg:apk/alpine/prometheus-openrc@2.27.1-r3?arch=ppc64le&distro=v3.14
- pkg:apk/alpine/prometheus-openrc@2.27.1-r3?arch=s390x&distro=v3.14
- pkg:apk/alpine/prometheus-openrc@2.27.1-r3?arch=x86&distro=v3.14
- pkg:apk/alpine/prometheus-openrc@2.27.1-r3?arch=x86_64&distro=v3.14
- pkg:apk/alpine/prometheus-openrc@2.31.1-r2?arch=aarch64&distro=v3.15
- pkg:apk/alpine/prometheus-openrc@2.31.1-r2?arch=armhf&distro=v3.15
- pkg:apk/alpine/prometheus-openrc@2.31.1-r2?arch=armv7&distro=v3.15
- pkg:apk/alpine/prometheus-openrc@2.31.1-r2?arch=ppc64le&distro=v3.15
- pkg:apk/alpine/prometheus-openrc@2.31.1-r2?arch=s390x&distro=v3.15
- pkg:apk/alpine/prometheus-openrc@2.31.1-r2?arch=x86&distro=v3.15
- pkg:apk/alpine/prometheus-openrc@2.31.1-r2?arch=x86_64&distro=v3.15
- pkg:apk/alpine/prometheus-openrc@2.35.0-r4?arch=aarch64&distro=v3.16
- pkg:apk/alpine/prometheus-openrc@2.35.0-r4?arch=armhf&distro=v3.16
- pkg:apk/alpine/prometheus-openrc@2.35.0-r4?arch=armv7&distro=v3.16
- pkg:apk/alpine/prometheus-openrc@2.35.0-r4?arch=ppc64le&distro=v3.16
- pkg:apk/alpine/prometheus-openrc@2.35.0-r4?arch=s390x&distro=v3.16
- pkg:apk/alpine/prometheus-openrc@2.35.0-r4?arch=x86&distro=v3.16
- pkg:apk/alpine/prometheus-openrc@2.35.0-r4?arch=x86_64&distro=v3.16
- pkg:apk/alpine/prometheus-openrc@2.40.5-r4?arch=aarch64&distro=v3.17
- pkg:apk/alpine/prometheus-openrc@2.40.5-r4?arch=armhf&distro=v3.17
- pkg:apk/alpine/prometheus-openrc@2.40.5-r4?arch=armv7&distro=v3.17
- pkg:apk/alpine/prometheus-openrc@2.40.5-r4?arch=ppc64le&distro=v3.17
- pkg:apk/alpine/prometheus-openrc@2.40.5-r4?arch=s390x&distro=v3.17
- pkg:apk/alpine/prometheus-openrc@2.40.5-r4?arch=x86&distro=v3.17
- pkg:apk/alpine/prometheus-openrc@2.40.5-r4?arch=x86_64&distro=v3.17
- pkg:apk/alpine/prometheus-openrc@2.42.0-r9?arch=aarch64&distro=v3.18
- pkg:apk/alpine/prometheus-openrc@2.42.0-r9?arch=armhf&distro=v3.18
- pkg:apk/alpine/prometheus-openrc@2.42.0-r9?arch=armv7&distro=v3.18
- pkg:apk/alpine/prometheus-openrc@2.42.0-r9?arch=ppc64le&distro=v3.18
- pkg:apk/alpine/prometheus-openrc@2.42.0-r9?arch=s390x&distro=v3.18
- pkg:apk/alpine/prometheus-openrc@2.42.0-r9?arch=x86&distro=v3.18
- pkg:apk/alpine/prometheus-openrc@2.42.0-r9?arch=x86_64&distro=v3.18
- pkg:apk/alpine/prometheus-openrc@2.48.0-r3?arch=aarch64&distro=v3.19
- pkg:apk/alpine/prometheus-openrc@2.48.0-r3?arch=armhf&distro=v3.19
- pkg:apk/alpine/prometheus-openrc@2.48.0-r3?arch=armv7&distro=v3.19
- pkg:apk/alpine/prometheus-openrc@2.48.0-r3?arch=ppc64le&distro=v3.19
- pkg:apk/alpine/prometheus-openrc@2.48.0-r3?arch=s390x&distro=v3.19
- pkg:apk/alpine/prometheus-openrc@2.48.0-r3?arch=x86&distro=v3.19
- pkg:apk/alpine/prometheus-openrc@2.48.0-r3?arch=x86_64&distro=v3.19
- pkg:apk/alpine/prometheus-openrc@2.52.0-r4?arch=aarch64&distro=v3.20
- pkg:apk/alpine/prometheus-openrc@2.52.0-r4?arch=armhf&distro=v3.20
- pkg:apk/alpine/prometheus-openrc@2.52.0-r4?arch=armv7&distro=v3.20
- pkg:apk/alpine/prometheus-openrc@2.52.0-r4?arch=ppc64le&distro=v3.20
- pkg:apk/alpine/prometheus-openrc@2.52.0-r4?arch=s390x&distro=v3.20
- pkg:apk/alpine/prometheus-openrc@2.52.0-r4?arch=x86&distro=v3.20
- pkg:apk/alpine/prometheus-openrc@2.52.0-r4?arch=x86_64&distro=v3.20
- pkg:apk/alpine/prometheus-openrc@2.53.2-r5?arch=aarch64&distro=v3.21
- pkg:apk/alpine/prometheus-openrc@2.53.2-r5?arch=armhf&distro=v3.21
- pkg:apk/alpine/prometheus-openrc@2.53.2-r5?arch=armv7&distro=v3.21
- pkg:apk/alpine/prometheus-openrc@2.53.2-r5?arch=loongarch64&distro=v3.21
- pkg:apk/alpine/prometheus-openrc@2.53.2-r5?arch=ppc64le&distro=v3.21
- pkg:apk/alpine/prometheus-openrc@2.53.2-r5?arch=riscv64&distro=v3.21
- pkg:apk/alpine/prometheus-openrc@2.53.2-r5?arch=s390x&distro=v3.21
- pkg:apk/alpine/prometheus-openrc@2.53.2-r5?arch=x86&distro=v3.21
- pkg:apk/alpine/prometheus-openrc@2.53.2-r5?arch=x86_64&distro=v3.21
- pkg:apk/alpine/prometheus-openrc@2.53.4-r5?arch=riscv64&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r6?arch=aarch64&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r6?arch=armhf&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r6?arch=armv7&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r6?arch=loongarch64&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r6?arch=ppc64le&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r6?arch=riscv64&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r6?arch=s390x&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r6?arch=x86&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r6?arch=x86_64&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r7?arch=aarch64&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r7?arch=armhf&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r7?arch=armv7&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r7?arch=loongarch64&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r7?arch=ppc64le&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r7?arch=s390x&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r7?arch=x86&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@2.53.4-r7?arch=x86_64&distro=v3.22
- pkg:apk/alpine/prometheus-openrc@3.5.0-r3?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-openrc@3.5.0-r3?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc@3.5.0-r3?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-openrc@3.5.0-r3?arch=armhf&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc@3.5.0-r3?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-openrc@3.5.0-r3?arch=armv7&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc@3.5.0-r3?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-openrc@3.5.0-r3?arch=x86_64&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc@3.5.0-r4?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-openrc@3.5.0-r4?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc@3.5.0-r4?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-openrc@3.5.0-r4?arch=armhf&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc@3.5.0-r4?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-openrc@3.5.0-r4?arch=armv7&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc@3.5.0-r4?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-openrc@3.5.0-r4?arch=x86_64&distro=latest-stable
- pkg:apk/alpine/prometheus-openrc@3.5.1-r0?arch=aarch64&distro=edge
