- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=loongarch64&distro=edge
