- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.0-r6?arch=aarch64&distro=v3.18
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.0-r6?arch=armhf&distro=v3.18
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.0-r6?arch=armv7&distro=v3.18
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.0-r6?arch=ppc64le&distro=v3.18
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.0-r6?arch=s390x&distro=v3.18
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.0-r6?arch=x86&distro=v3.18
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.0-r6?arch=x86_64&distro=v3.18
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.2-r3?arch=aarch64&distro=v3.19
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.2-r3?arch=armhf&distro=v3.19
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.2-r3?arch=armv7&distro=v3.19
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.2-r3?arch=ppc64le&distro=v3.19
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.2-r3?arch=s390x&distro=v3.19
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.2-r3?arch=x86&distro=v3.19
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.6.2-r3?arch=x86_64&distro=v3.19
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r4?arch=aarch64&distro=v3.20
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r4?arch=armhf&distro=v3.20
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r4?arch=armv7&distro=v3.20
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r4?arch=ppc64le&distro=v3.20
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r4?arch=riscv64&distro=v3.20
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r4?arch=s390x&distro=v3.20
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r4?arch=x86&distro=v3.20
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r4?arch=x86_64&distro=v3.20
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r9?arch=aarch64&distro=v3.21
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r9?arch=armhf&distro=v3.21
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r9?arch=armv7&distro=v3.21
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r9?arch=loongarch64&distro=v3.21
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r9?arch=ppc64le&distro=v3.21
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r9?arch=riscv64&distro=v3.21
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r9?arch=s390x&distro=v3.21
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r9?arch=x86&distro=v3.21
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.7.0-r9?arch=x86_64&distro=v3.21
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=aarch64&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=armhf&distro=latest-stable
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=armhf&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=armv7&distro=latest-stable
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=armv7&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=loongarch64&distro=latest-stable
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=loongarch64&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=ppc64le&distro=latest-stable
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=riscv64&distro=latest-stable
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=s390x&distro=latest-stable
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=x86&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=x86&distro=latest-stable
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r10?arch=x86_64&distro=latest-stable
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r8?arch=riscv64&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r9?arch=aarch64&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r9?arch=armhf&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r9?arch=armv7&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r9?arch=loongarch64&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r9?arch=ppc64le&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r9?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r9?arch=riscv64&distro=latest-stable
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r9?arch=riscv64&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r9?arch=s390x&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r9?arch=x86&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.8.0-r9?arch=x86_64&distro=v3.22
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r0?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r0?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r0?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r0?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r0?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r0?arch=riscv64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r0?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r0?arch=x86&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r0?arch=x86_64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r1?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r1?arch=ppc64le&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r1?arch=s390x&distro=edge
- pkg:apk/alpine/prometheus-nextcloud-exporter-openrc@0.9.0-r1?arch=x86_64&distro=edge
