- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r18?arch=aarch64&distro=v3.19
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r18?arch=armhf&distro=v3.19
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r18?arch=armv7&distro=v3.19
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r18?arch=ppc64le&distro=v3.19
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r18?arch=s390x&distro=v3.19
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r18?arch=x86&distro=v3.19
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r18?arch=x86_64&distro=v3.19
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r20?arch=aarch64&distro=v3.20
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r20?arch=armhf&distro=v3.20
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r20?arch=armv7&distro=v3.20
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r20?arch=ppc64le&distro=v3.20
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r20?arch=riscv64&distro=v3.20
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r20?arch=s390x&distro=v3.20
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r20?arch=x86&distro=v3.20
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r20?arch=x86_64&distro=v3.20
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r21?arch=aarch64&distro=v3.21
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r21?arch=armhf&distro=v3.21
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r21?arch=armv7&distro=v3.21
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r21?arch=loongarch64&distro=v3.21
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r21?arch=ppc64le&distro=v3.21
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r21?arch=riscv64&distro=v3.21
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r21?arch=s390x&distro=v3.21
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r21?arch=x86&distro=v3.21
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r21?arch=x86_64&distro=v3.21
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=aarch64&distro=edge
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=aarch64&distro=latest-stable
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=aarch64&distro=v3.22
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=armhf&distro=edge
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=armhf&distro=latest-stable
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=armhf&distro=v3.22
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=armv7&distro=edge
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=armv7&distro=latest-stable
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=armv7&distro=v3.22
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=loongarch64&distro=edge
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=loongarch64&distro=latest-stable
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=loongarch64&distro=v3.22
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=ppc64le&distro=edge
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=ppc64le&distro=latest-stable
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=ppc64le&distro=v3.22
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=riscv64&distro=edge
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=riscv64&distro=latest-stable
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=riscv64&distro=v3.22
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=s390x&distro=edge
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=s390x&distro=latest-stable
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=s390x&distro=v3.22
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=x86&distro=edge
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=x86&distro=latest-stable
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=x86&distro=v3.22
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=x86_64&distro=edge
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=x86_64&distro=latest-stable
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r23?arch=x86_64&distro=v3.22
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r24?arch=aarch64&distro=edge
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r24?arch=loongarch64&distro=edge
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r24?arch=ppc64le&distro=edge
- pkg:apk/alpine/collectd-write_prometheus@5.12.0-r24?arch=s390x&distro=edge
