- pkg:apk/alpine/prometheus-node-exporter@1.10.2-r0?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-node-exporter@1.10.2-r0?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-node-exporter@1.10.2-r0?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-node-exporter@1.10.2-r0?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-node-exporter@1.10.2-r0?arch=ppc64le&distro=edge
