- pkg:apk/alpine/prometheus-smtp2go-exporter@0.1.1-r4?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-smtp2go-exporter@0.1.1-r4?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-smtp2go-exporter@0.1.1-r4?arch=armv7&distro=edge
