- pkg:apk/alpine/prometheus-libvirt-exporter@2.3.3-r19?arch=aarch64&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter@2.3.3-r19?arch=armhf&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter@2.3.3-r19?arch=armv7&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter@2.3.3-r19?arch=loongarch64&distro=edge
- pkg:apk/alpine/prometheus-libvirt-exporter@2.3.3-r19?arch=ppc64le&distro=edge
